name: Lint & Test Chart

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  chart-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0
      - name: Run lint check
        id: lint
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
      - name: Create kind cluster
        if: steps.lint.outcome == 'success'
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - name: Run chart-testing (install)
        if: steps.lint.outcome == 'success'
        run: |
          ct install --target-branch ${{ github.event.repository.default_branch }} --helm-extra-args --timeout 180s
